"use client"

import { useEffect, useState } from "react"
import { useRouter } from "next/navigation"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Textarea } from "@/components/ui/textarea"
import { ArrowLeft, Save } from "lucide-react"
import Link from "next/link"
import { LogoUpload } from "@/components/admin/logo-upload"

interface Category {
  id: string
  name: string
  slug: string
}

export default function NewCategoryPage() {
  const router = useRouter()
  const [loading, setLoading] = useState(true)
  const [saving, setSaving] = useState(false)
  const [error, setError] = useState("")
  const [categories, setCategories] = useState<Category[]>([])

  const [formData, setFormData] = useState({
    name: "",
    slug: "",
    parentId: "",
    image: "",
    description: "",
    seoTitle: "",
    seoDescription: "",
  })

  useEffect(() => {
    const fetchCategories = async () => {
      try {
        const res = await fetch("/api/categories")
        const data = await res.json()
        setCategories(data)
      } catch (err: any) {
        setError(err.message || "Erreur lors du chargement")
      } finally {
        setLoading(false)
      }
    }

    fetchCategories()
  }, [])

  // Générer le slug automatiquement à partir du nom
  const generateSlug = (name: string) => {
    return name
      .toLowerCase()
      .normalize("NFD")
      .replace(/[\u0300-\u036f]/g, "")
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/(^-|-$)/g, "")
  }

  const handleNameChange = (name: string) => {
    // Toujours générer le slug automatiquement à partir du nom
    // Sauf si l'utilisateur a modifié manuellement le slug et qu'il est différent du slug généré
    const autoGeneratedSlug = generateSlug(name)
    const currentSlug = formData.slug || ""
    const previousAutoSlug = generateSlug(formData.name || "")
    
    // Si le slug actuel est vide, correspond au slug auto-généré précédent, ou est identique au slug qui serait généré, on le met à jour
    const shouldAutoGenerate = !currentSlug || currentSlug === previousAutoSlug || currentSlug === autoGeneratedSlug
    
    setFormData({
      ...formData,
      name,
      slug: shouldAutoGenerate ? autoGeneratedSlug : (currentSlug || autoGeneratedSlug),
    })
  }

  const handleSlugChange = (slug: string) => {
    // Normaliser le slug en temps réel lors de la saisie manuelle
    const normalized = generateSlug(slug)
    setFormData({ ...formData, slug: normalized })
  }

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    setError("")
    setSaving(true)

    try {
      // Validation
      if (!formData.name.trim()) {
        throw new Error("Le nom est requis")
      }

      // S'assurer que le slug est toujours généré
      const finalSlug = formData.slug.trim() || generateSlug(formData.name)
      if (!finalSlug) {
        throw new Error("Le slug est requis")
      }

      const payload = {
        name: formData.name.trim(),
        slug: finalSlug,
        parentId: formData.parentId || null,
        image: formData.image || null,
        description: formData.description || null,
        seoTitle: formData.seoTitle || null,
        seoDescription: formData.seoDescription || null,
      }

      const res = await fetch("/api/categories", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(payload),
      })

      if (!res.ok) {
        const errorData = await res.json()
        throw new Error(errorData.error || "Erreur lors de la création")
      }

      router.push("/admin/categories")
      router.refresh()
    } catch (err: any) {
      setError(err.message || "Erreur lors de la sauvegarde")
    } finally {
      setSaving(false)
    }
  }

  if (loading) {
    return (
      <div className="space-y-6">
        <div>Chargement...</div>
      </div>
    )
  }

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold text-foreground">Nouvelle catégorie</h1>
          <p className="text-muted-foreground mt-2">
            Créer une nouvelle catégorie ou sous-catégorie
          </p>
        </div>
        <Button variant="outline" asChild>
          <Link href="/admin/categories">
            <ArrowLeft className="w-4 h-4 mr-2" />
            Retour
          </Link>
        </Button>
      </div>

      <form onSubmit={handleSubmit}>
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          <Card>
            <CardHeader>
              <CardTitle>Informations générales</CardTitle>
              <CardDescription>Détails de base de la catégorie</CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="space-y-2">
                <Label htmlFor="name">Nom *</Label>
                <Input
                  id="name"
                  value={formData.name}
                  onChange={(e) => handleNameChange(e.target.value)}
                  required
                />
              </div>

              <div className="space-y-2">
                <Label htmlFor="slug">Slug (URL) *</Label>
                <Input
                  id="slug"
                  value={formData.slug}
                  onChange={(e) => handleSlugChange(e.target.value)}
                  required
                  placeholder="auto-généré depuis le nom"
                  onBlur={(e) => {
                    // Si le slug est vide au blur, le générer depuis le nom
                    if (!e.target.value && formData.name) {
                      handleSlugChange(generateSlug(formData.name))
                    }
                  }}
                />
                <p className="text-xs text-muted-foreground">
                  Version URL-friendly du nom (ex: "electronique" pour "Électronique"). Généré automatiquement à partir du nom.
                </p>
              </div>

              <div className="space-y-2">
                <Label htmlFor="parentId">Catégorie parente</Label>
                <select
                  id="parentId"
                  className="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"
                  value={formData.parentId}
                  onChange={(e) => setFormData({ ...formData, parentId: e.target.value })}
                >
                  <option value="">Aucune (catégorie racine)</option>
                  {categories.map((cat) => (
                    <option key={cat.id} value={cat.id}>
                      {cat.name}
                    </option>
                  ))}
                </select>
              </div>

              <div className="space-y-2">
                <Label htmlFor="description">Description</Label>
                <Textarea
                  id="description"
                  value={formData.description}
                  onChange={(e) => setFormData({ ...formData, description: e.target.value })}
                  rows={4}
                />
              </div>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>Image et SEO</CardTitle>
              <CardDescription>Image de la catégorie et optimisation SEO</CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="space-y-2">
                <LogoUpload
                  value={formData.image}
                  onChange={(url) => setFormData({ ...formData, image: url })}
                />
              </div>

              <div className="space-y-2">
                <Label htmlFor="seoTitle">Titre SEO</Label>
                <Input
                  id="seoTitle"
                  value={formData.seoTitle}
                  onChange={(e) => setFormData({ ...formData, seoTitle: e.target.value })}
                  placeholder="Titre optimisé pour les moteurs de recherche"
                />
              </div>

              <div className="space-y-2">
                <Label htmlFor="seoDescription">Description SEO</Label>
                <Textarea
                  id="seoDescription"
                  value={formData.seoDescription}
                  onChange={(e) => setFormData({ ...formData, seoDescription: e.target.value })}
                  rows={3}
                  placeholder="Description optimisée pour les moteurs de recherche"
                />
              </div>
            </CardContent>
          </Card>
        </div>

        {error && (
          <Card className="mt-6 border-destructive">
            <CardContent className="pt-6">
              <div className="text-sm text-destructive">{error}</div>
            </CardContent>
          </Card>
        )}

        <div className="mt-6 flex justify-end gap-4">
          <Button type="button" variant="outline" asChild>
            <Link href="/admin/categories">Annuler</Link>
          </Button>
          <Button type="submit" disabled={saving}>
            <Save className="w-4 h-4 mr-2" />
            {saving ? "Création..." : "Créer la catégorie"}
          </Button>
        </div>
      </form>
    </div>
  )
}
